<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxSgn0Y\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxSgn0Y/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYxSgn0Y.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYxSgn0Y\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYxSgn0Y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YxSgn0Y',
    'container.build_id' => '11de66bd',
    'container.build_time' => 1700994013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxSgn0Y');
