<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTHCPHQ0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTHCPHQ0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTHCPHQ0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTHCPHQ0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTHCPHQ0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'THCPHQ0',
    'container.build_id' => 'f68728f0',
    'container.build_time' => 1700996724,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTHCPHQ0');
